name: Tests

on:
  pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7.4
        ports:
          - 6379:6379
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: lab
        ports:
          - 3306:3306

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          php-version: '8.3'

      - name: Install Project Dependencies
        run: composer install -q --no-interaction --no-progress

      - name: Prepare application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Test
        run: php artisan test --compact --coverage --min=75
