name: Tests

on:
  pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7.4
        ports:
          - 6379:6379
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: lab
        ports:
          - 3306:3306

    env:
      PHP_VERSION: '8.3'
      CACHE_KEY: extension-cache-v1
      PHP_EXTENSIONS: dom, curl, libxml, mbstring, zip, pcntl, pdo, gd, redis, igbinary, msgpack, lzf, zstd, lz4, memcached, gmp, :php-psr

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          key: ${{ env.CACHE_KEY }}

      - name: Cache extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          tools: composer:v2

      - name: Get composer cache dir
        id: composer-cache-dir
        run: echo dir=$(composer config cache-files-dir) >> $GITHUB_OUTPUT

      - name: Cache Dependencies
        uses: actions/cache@v4.1.2
        with:
          key: composer-cache-${{ hashFiles('**/composer.lock') }}
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          restore-keys: composer-cache-

      - name: Install Project Dependencies
        run : composer install -q --no-interaction --no-progress

      - name: Prepare application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Test
        run: php artisan test --compact
